name: Weekly Newsletter

on:
  schedule:
    # 毎週火曜 08:30 JST（= 月曜23:30 UTC）
    - cron: '30 23 * * 1'
  workflow_dispatch: {}

jobs:
  build-send:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          pip install -r requirements.txt

      - name: Generate newsletter content (HTML only)
        run: python scripts/generate_newsletter.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Send with SendGrid
        run: |
          html=$(cat email.html)
          list_id=${SG_LIST_ID}

          jq -n --arg html "$html" --arg list_id "$list_id" '
          {
            personalizations: [{
              to: [],
              list_ids: [$list_id],
              subject: "【2112】週刊 Road to 2112"
            }],
            from: {
              email: "info@sassamahha.me",
              name: "Jun Sasaki"
            },
            content: [{
              type: "text/html",
              value: $html
            }]
          }' > payload_ready.json

          curl -s --request POST \
            --url https://api.sendgrid.com/v3/mail/send \
            --header "Authorization: Bearer $SENDGRID_API_KEY" \
            --header "Content-Type: application/json" \
            --data @payload_ready.json
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SG_LIST_ID: ${{ secrets.SG_LIST_ID }}

