# .github/workflows/newsletter_ja.yml
name: send-nl-ja

on:
  schedule:       # 火曜 08:30 JST
    - cron: '30 23 * * 1'
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    env:
      LANG: "ja"
      LIST_ID: ${{ secrets.SENDGRID_LIST_ID_JA }}
      FEED_URLS: |
        https://studyriver.jp/feed/
        https://sassamahha.me/feed/
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Generate & Send
        run: |
          python scripts/generate_newsletter.py \
            --lang "$LANG" \
            --list-id "$LIST_ID" \
            --feeds "$FEED_URLS"
